version: "3.8"

services:

  yolo-client:
    build: ./client
    image: edwinkorir38/yolo-client:v1.0.1
    container_name: yolo-client
    ports:
      - "3000:80"
    depends_on:
      - yolo-backend
    networks:
      - app-net
    environment:
      - REACT_APP_API_URL=http://yolo-backend:5000/api

  yolo-backend:
    build: ./backend
    image: edwinkorir38/yolo-backend:v1.0.0
    container_name: yolo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - yolo-mongo
    networks:
      - app-net
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://yolo-mongo:27017/yoloDB

  yolo-mongo:
    image: mongo:6
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    volumes:
      - app-mongo-data:/data/db

networks:
  app-net:
    driver: bridge

volumes:
  app-mongo-data:
    driver: local
