---
- name: Pull image from repository
  docker_image:
    name: edwinkorir38/brian-yolo-backend:v1.0.0
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: yolo-backend
    image: edwinkorir38/yolo-backend:v1.0.0
    networks:
      - name: app-net
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes